# Schema for Scheduler module configuration.

scheduler.settings:
  type: mapping
  label: 'Scheduler settings'
  mapping:
    allow_date_only:
      type: boolean
    date_format:
      type: string
    date_only_format:
      type: string
    default_time:
      type: string
    lightweight_cron_access_key:
      type: string
    log:
      type: boolean
    time_only_format:
      type: string
    langcode:        # Added langcode to avoid fatal error in simpletests.
      type: string   # @TODO But is it correct? Why should we need LANGCODE in Scheduler settings?

node_type.third_party.scheduler:
  type: mapping
  label: 'Scheduler content type settings'
  mapping:
    publish_enable:
      type: boolean
      label: 'Enable scheduled publishing'
    publish_past_date:
      type: string
      label: 'Action to be taken for publication dates in the past'
    publish_required:
      type: boolean
      label: 'Require scheduled publishing'
    publish_revision:
      type: boolean
      label: 'Create a new revision on publishing'
    publish_touch:
      type: boolean
      label: 'Change content creation time to match the scheduled publish time'
    unpublish_enable:
      type: boolean
      label: 'Enable scheduled unpublishing'
    unpublish_required:
      type: boolean
      label: 'Require scheduled unpublishing'
    unpublish_revision:
      type: boolean
      label: 'Create a new revision on unpublishing'
    use_vertical_tabs: # Added this to avoid fatal error in simpletests.
      type: boolean    # @TODO verify that this is OK, then remove the comment.
